- name: Install Python
  ansible.builtin.yum:
    name: "{{item}}"
    state: installed
  loop:
    - python36
    - gcc
    - python3-devel

- name: setup application
  ansible.builtin.import_role:
    name: common #dir
    tasks_from: app_setup

- name: Install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: system reloads
  ansible.builtin.import_role:
    name: common #dir
    tasks_from: systemd_setup
