- name: installing go language
  ansible.builtin.yum:
    name: golang
    state: installed

- name: setup application
  ansible.builtin.import_role:
    name: common #dir
    tasks_from: app_setup

- name: Install dependencies
  ansible.builtin.command: "go {{item}}"
  loop:
    - mod init dispatch
    - get
    - build
  args:
    chdir: /app

- name: system reloads
  ansible.builtin.import_role:
    name: common #dir
    tasks_from: systemd_setup
