- name: check roboshop user existence
  ansible.builtin.command: id roboshop
  register: output
  ignore_errors: true
- when: output.rc != 0
  become: yes
  ansible.builtin.user:
    name: roboshop

- name: creating directory /app
  ansible.builtin.stat:
    path: /app
  register: directory
- when: directory.stat.exists == false
  ansible.builtin.file:
    path: /app
    state: directory

- name: download the "{{component}}" code artifact
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: extract the zip file downloaded
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes
