#refer nodejs installation tasks from common/tasks.nodejs.yaml
#importing nodejs installing code from commons dir
- name: installing nodejs
  ansible.builtin.import_role:
    name: common #dir
    tasks_from: nodejs # file name without ext

- name: setup application
  ansible.builtin.import_role:
    name: common #dir
    tasks_from: app_setup # file name without ext

- name: install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: system reloads
  ansible.builtin.import_role:
    name: common #dir
    tasks_from: systemd_setup # file name without ext

- name: load schema
  ansible.builtin.import_role:
    name: common #dir
    tasks_from: load_schema # file name without ext

- name: loading the schema
  ansible.builtin.command: mongo --host mongodb.mydomainproject.tech < /app/schema/catalogue.js

- name: restart catalogue service
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: true
