- name: setting up mysql
  hosts: mysql
  become: yes
  tasks:
    - name: Disable current MySQL version
      ansible.builtin.command: yum module disable mysql -y

    - name: copy mysql.repo
      ansible.builtin.copy:
        src: 07.01-mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: installing mysql
      ansible.builtin.yum:
        name: mysql-community-server
        state: installed

    - name: start mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true

    - name: setup mysql root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
